const ecommerce = "/assets/images/ecommerce.webp";
const learnsphere = "/assets/images/learnsphere.webp";
const cloud_saas = "/assets/images/cloud_saas.webp";
const endpointhub = "/assets/images/endpointhub.webp";
const routelink = "/assets/images/routelink.webp";
const monositi = "/assets/images/monositi.webp";
const recipe_finder = "/assets/images/recipefinder.webp";
const music_player = "/assets/images/music_player.webp";
const classcrew = "/assets/images/classcrew.webp";
const gem_control = "/assets/images/gem_control.webp";

const image1 = "/assets/images/yourbeep/Homepage.avif"
const image2 = "/assets/images/yourbeep/15.avif"
const image3 = "/assets/images/yourbeep/Heart.avif"

const ironstreak_dashboard = "/assets/images/ironstreak/dashboard.webp";
const ironstreak_diet = "/assets/images/ironstreak/diet.webp";
const ironstreak_stats = "/assets/images/ironstreak/stats.webp";

const githubstats_profile = "/assets/images/githubstats/profile.webp";
const githubstats_skills = "/assets/images/githubstats/skills.webp";
const githubstats_activity = "/assets/images/githubstats/activity.webp";

const blip_suggest = "/assets/images/blip/suggest.webp";
const blip_picker = "/assets/images/blip/picker.webp";
const blip_manager = "/assets/images/blip/manager.webp";
const blipImages = [blip_suggest, blip_picker, blip_manager];

export const projectsData = [
  {
    id: 13,
    title: "Blip",
    image: blipImages,
    description:
      "Local-first text expander for Chrome and Brave that also notices what you retype and offers to save it, without ever storing the text itself",
    tech: ["JavaScript", "Manifest V3", "Chrome Extension APIs", "Shadow DOM"],
    category: "Browser Extension / Developer Tool",
    year: "2026",
    summary:
      "Type ;;pr in any text box on any site and it expands into your saved snippet. No account, no server, no network calls anywhere in the codebase.",
    fullDescription:
      "Blip is a Manifest V3 text expander built to work correctly inside the two incompatible input models the web actually has: plain <input>/<textarea> elements and contenteditable divs used by Gmail, ChatGPT, Claude, Notion, and Slack. Insertion goes through document.execCommand('insertText') rather than direct DOM assignment, because React-controlled inputs silently discard a plain .value write on the next render — execCommand fires the same native input events a real keystroke would, so framework state stays correct and the browser's own undo stack still works. The picker that appears mid-typing is positioned using a caret-mirroring technique, since plain inputs expose no API for a caret's on-screen coordinates. The standout feature is a repeat detector: after you retype the same text three times, it offers to save it as a snippet — but it stores only a hash and a count, never the text, so the suggestion can quote you back without ever having kept a copy.",
    features: [
      "Expansion works identically inside <input>/<textarea> and contenteditable editors",
      "Insertion via document.execCommand('insertText') so React/Vue-controlled inputs update correctly and native undo still works",
      "Caret-position picker for ambiguous shortcuts, rendered in a closed shadow root so host page CSS/JS can't reach it",
      "Repeat detector that suggests new snippets after three sightings, storing a hash and count only — never the captured text",
      "Placeholders for {{cursor}}, {{clipboard}}, {{date}}, and other dynamic tokens",
      "Neo-brutalist UI (hard shadows, no gradients) built entirely in vanilla JS/CSS, no framework dependency",
    ],
    challenges: [
      "Normalising two incompatible text-input models (.value vs. DOM Selection/contenteditable) behind one API",
      "Writing into React-controlled inputs without the framework silently reverting the change on its next render",
      "Positioning a picker at the caret inside a plain <input>, which exposes no caret-coordinate API at all",
      "Designing a 'notices what you retype' feature that is genuinely useful without ever storing what the user typed",
    ],
    liveLink: "",
    githubLink: "https://github.com/Sachinsen7/blip",
    timeline: [
      { phase: "Core matching engine & dual input-model support", duration: "1 day", status: "completed" },
      { phase: "React-safe insertion & shadow-DOM picker UI", duration: "1 day", status: "completed" },
      { phase: "Repeat detector with hash-only storage", duration: "1 day", status: "completed" },
    ],
    team: "Solo Project",
    role: "Extension Developer",
    status: "Shipped / Open Source",
    duration: "1 day",
  },
  {
    id: 14,
    title: "Blip Desktop",
    image: blipImages,
    description:
      "System-wide text expansion for Windows, written in Rust — the same idea as Blip, but working in every application, not just the browser",
    tech: ["Rust", "Tauri", "Win32 API", "WebView2"],
    category: "Desktop Application / Systems Programming",
    year: "2026",
    summary:
      "A low-level Windows keyboard hook that expands text in VS Code, Slack, Word, or a terminal, with a tray icon and a native manager window.",
    fullDescription:
      "Blip Desktop reimplements Blip's expansion engine as a native Windows service using a WH_KEYBOARD_LL hook, which sees every keystroke on the system before the focused application does. Getting reliable text injection working was the real engineering problem: SendInput must be called as a single atomic batch, not split into smaller paced calls, or the user's own concurrent keystrokes can interleave with injected ones and corrupt the output. A second, subtler bug came from a key-suppression flag that could get stuck permanently if a key's release event was ever reordered during injection, silently eating every future press of that letter — found only by adding an instrumentation flag that logs the exact payload the engine intends to send, rather than by guessing further. Long snippets are delivered via a clipboard-paste fallback instead of simulated keystrokes, which sidesteps the timing-sensitive path entirely for anything over a dozen characters. The manager window is a Tauri app that reuses Blip's browser-extension UI almost unchanged, talking to the same in-memory engine state the keyboard hook reads, so an edit takes effect on the very next keystroke with no restart.",
    features: [
      "System-wide expansion via a low-level Windows keyboard hook (WH_KEYBOARD_LL)",
      "Layout-aware key translation via ToUnicodeEx, so non-US keyboard layouts work correctly",
      "Atomic SendInput injection with a clipboard-paste fallback for long or multi-line snippets",
      "System tray with a live enable/disable toggle and a manager window entry point",
      "Tauri-based manager window sharing the browser extension's UI and design system",
      "Snippet edits in the window take effect immediately — no restart, no polling, direct shared state",
    ],
    challenges: [
      "SendInput corrupted output when paced into smaller batches; the fix was recognising it must be called as one atomic batch, not smaller ones",
      "A key-suppression flag could get stuck permanently if a release event was reordered during heavy injection, silently swallowing future keystrokes",
      "Diagnosing intermittent corruption required building debug instrumentation to log intended payloads, rather than continuing to guess at timing fixes",
      "An uninitialised Win32 INPUT union (larger MOUSEINPUT variant sharing memory with the smaller KEYBDINPUT one) passed garbage bytes to the kernel until explicitly zeroed",
      "Keeping a GUI (Tauri/WebView2) and a headless console binary sharing one engine crate with zero UI-framework coupling",
    ],
    liveLink: "",
    githubLink: "https://github.com/Sachinsen7/blip-desktop",
    timeline: [
      { phase: "Keyboard hook, matcher engine, text injection", duration: "1 day", status: "completed" },
      { phase: "Debugging SendInput corruption & stuck-key suppression bug", duration: "1 day", status: "completed" },
      { phase: "System tray, clipboard fallback, Tauri manager window", duration: "1 day", status: "completed" },
    ],
    team: "Solo Project",
    role: "Systems / Desktop Developer",
    status: "Shipped / Open Source",
    duration: "3 days",
  },
  {
    id: 15,
    title: "Self-Hosted GitHub Profile Stats",
    image: [githubstats_profile, githubstats_skills, githubstats_activity],
    description:
      "A reliability-first alternative to the usual GitHub profile stat-card services, which generates SVG cards via GitHub Actions instead of a live server",
    tech: ["Node.js", "GitHub Actions", "GitHub REST API", "SVG"],
    category: "Developer Tooling / Automation",
    year: "2026",
    summary:
      "github-readme-stats and github-profile-trophy were both deployment-paused the same week I needed them, so I built a version that structurally can't go down.",
    fullDescription:
      "Popular GitHub profile widgets like github-readme-stats render an SVG live, on every profile view, from a single shared free-tier server — which is exactly why they periodically go down under load. This project avoids that failure mode by architecture rather than by hoping for better uptime: a GitHub Action runs on a schedule, calls the GitHub REST API directly, renders three SVG cards from scratch (no external stats library), and commits them straight into the repository. The images the profile README displays are then just static files GitHub itself serves — no shared server to overload, no free-tier deployment to get paused. Because each run's results are committed to git, the stats card can show real trend deltas (\"+3 stars since last run\") between updates, something a stateless live-rendering service structurally cannot do. Brand icons for the skills row are vendored once from Simple Icons (CC0/public domain) directly into the script, so even the icon set carries no runtime dependency on anything outside the repo.",
    features: [
      "Zero live rendering dependency — GitHub Actions generates and commits static SVGs on a schedule",
      "Real trend deltas between runs, enabled by committing a small state snapshot to git each run",
      "Hand-rolled SVG card renderer (stats, top languages, 14-day activity flow, skills) with no external stats library",
      "Real technology brand icons vendored once from a public-domain icon set, never fetched at render time",
      "Runs against the real GitHub API with authenticated rate limits via the Actions-provided token",
    ],
    challenges: [
      "Diagnosing that github-readme-stats' outage was a paused shared deployment, not a config issue — verified by loading the endpoint directly rather than guessing",
      "Designing around GitHub's unauthenticated API rate limit (60/hr) during local testing versus the Action's authenticated 5,000/hr",
      "Fixing a real legibility bug where inactive activity cells were rendered at the same fill colour as the card background, making most of the strip invisible",
      "Keeping the whole card set genuinely dependency-free — including vendoring icon path data rather than fetching it live",
    ],
    liveLink: "https://github.com/Sachinsen7/Sachinsen7",
    githubLink: "https://github.com/Sachinsen7/Sachinsen7",
    timeline: [
      { phase: "SVG card generator & GitHub Actions pipeline", duration: "1 day", status: "completed" },
      { phase: "Design iteration & real technology icons", duration: "1 day", status: "completed" },
    ],
    team: "Solo Project",
    role: "Automation / Tooling Developer",
    status: "Live",
    duration: "2 days",
  },
  {
    id: 16,
    title: "IronStreak",
    image: [ironstreak_dashboard, ironstreak_diet, ironstreak_stats],
    description:
      "Personal gym, diet, and streak-tracking PWA with a Duolingo-style gamification layer and self-photographed food logging",
    tech: [
      "React 19",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "Framer Motion",
      "Node.js",
      "Express",
      "Prisma",
      "PostgreSQL",
      "Vercel",
      "Netlify",
      "Cloudinary",
      "Nodemailer",
      "Zod",
      "JWT",
    ],
    category: "Mobile-First PWA / Full Stack",
    year: "2026",
    summary:
      "A self-use gym tracker built the same week I started training — workout logging, a food-photo diet log, and Duolingo-style streaks/XP, shipped as an installable PWA.",
    fullDescription:
      "IronStreak is a mobile-first Progressive Web App I built for my own daily gym and diet tracking, pairing a Node/Express/Prisma backend with a React 19/Vite/Tailwind v4 frontend. Workouts run against a configurable weekly split with per-set logging and per-exercise history; diet tracking centers on a swipeable carousel of foods I've actually photographed myself and uploaded via signed, server-side Cloudinary requests, with full macro and fiber tracking, rather than a generic packaged food database. Progress is gamified with streaks, XP levels, and badges, backed by an email layer — instant workout-completion summaries plus a secured cron endpoint for daily membership-expiry and streak-at-risk reminders that keeps working even on a serverless free tier. The backend ships as a Vercel serverless function behind a thin Express-to-serverless wrapper; the frontend deploys separately to Netlify; the two talk over a CORS-locked REST API.",
    features: [
      "Weekly workout split editor with per-exercise target sets/reps and per-session set logging",
      "Exercise history view charting past weight/reps per exercise",
      "Swipeable food card carousel with camera/gallery photo capture, uploaded via signed Cloudinary requests (API secret never reaches the browser)",
      "Long-press context menu on food cards for inline edit/delete",
      "Full macro tracking (calories, protein, carbs, fat, fiber) with a 5-ring daily progress dashboard",
      "Streak, XP/level, and badge gamification with confetti and haptic feedback on workout completion",
      "Gym membership tracker with days-left countdown, duration, and fees",
      "Light/dark/system theming with no flash-of-wrong-theme on load",
      "Installable PWA with offline shell via vite-plugin-pwa",
      "Email notifications: instant workout summaries plus daily membership-expiry and streak-at-risk reminders via a secured cron endpoint",
    ],
    challenges: [
      "Refactoring the Express app to run as a Vercel serverless function (splitting app construction from the dev-only listen() call) while keeping the daily-cron logic serverless-safe",
      "Tracking down a UTF-8 BOM silently prepended to every environment variable by PowerShell's pipe-to-stdin encoding when setting them via the Vercel CLI, which broke the Postgres connection string until switching to the CLI's --value flag",
      "A Zod .optional() schema rejecting the null a nullable Prisma field returns on GET, breaking the edit-then-save round trip on the membership form",
      "Removing a capture=\"environment\" attribute that was silently forcing the camera open instead of showing Android's normal photo picker",
      "Building a scroll-snap food carousel with spring-animated active-card scaling driven by manual scroll-position tracking rather than a carousel library",
    ],
    liveLink: "https://ironstreak-995.netlify.app",
    githubLink: "https://github.com/Sachinsen7/ironstreak",
    timeline: [
      { phase: "Backend: schema, auth, workout/diet/notification APIs, Vercel serverless refactor", duration: "1 day", status: "completed" },
      { phase: "Frontend: design system, screens, food photo uploads, theming, PWA, deployment", duration: "1 day", status: "completed" },
    ],
    team: "Solo Project",
    role: "Full Stack Developer",
    status: "Live",
    duration: "2 days",
  },
  {
    id: 11,
    title: "YourBeep",
    image: [
      image1,
      image2,
      image3,
    ],
    description:
      "Social and content platform combining short-form video, live streaming, community games, and courses across web, mobile, and admin apps",
    tech: [
      "React 19",
      "Three.js",
      "React Three Fiber",
      "Redux Toolkit",
      "Firebase",
      "HLS.js",
      "Expo",
      "React Native",
      "Bun",
      "Express",
      "MongoDB",
      "Tailwind CSS",
      "Framer Motion",
    ],
    category: "Social Platform (Web + Mobile + Microservices)",
    year: "2026",
    summary:
      "A social/content platform spanning a 3D-accented web app, a native mobile app, and a Bun-based microservice backend.",
    fullDescription:
      "YourBeep is a social and content platform built across three surfaces: a React 19 web app with Three.js-powered 3D touches and HLS video streaming through a Bunny CDN pipeline, an Expo/React Native mobile app, and a dedicated admin panel for content and commerce operations. The backend is a Bun-based microservice architecture split into gateway, identity, content, and commerce services backed by MongoDB, with Firebase handling authentication. The platform includes community games and course content alongside its core social feed and video experience.",
    features: [
      "Web app built with React 19, Three.js/React Three Fiber for 3D UI moments, and Firebase auth",
      "HLS video streaming via Bunny CDN with Plyr playback controls",
      "Native mobile app built with Expo and React Native, sharing Redux Toolkit state with the web client",
      "Bun-based microservice backend split into gateway, identity, content, and commerce services",
      "MongoDB data layer per service behind a shared API gateway",
      "Separate admin panel for managing content, users, and commerce",
      "Community games and course content modules",
      "Dockerized deployment configuration for the backend services",
    ],
    challenges: [
      "Coordinating a single product across three separate clients (web, mobile, admin) sharing one backend",
      "Designing a Bun microservice split (gateway/identity/content/commerce) with clean service boundaries",
      "Integrating HLS video streaming and CDN delivery for a smooth playback experience",
      "Bringing 3D interactions into a React web app without hurting load performance",
      "Keeping authentication and session handling consistent across Firebase-backed web and mobile clients",
    ],
    liveLink: "https://yourbeep.com",
    githubLink: "",
    timeline: [
      {
        phase: "Backend Microservices (Gateway, Identity, Content, Commerce)",
        duration: "Ongoing",
        status: "in-progress",
      },
      {
        phase: "Web App (React, Three.js, Video Streaming)",
        duration: "Ongoing",
        status: "in-progress",
      },
      {
        phase: "Mobile App (Expo / React Native)",
        duration: "Ongoing",
        status: "in-progress",
      },
      {
        phase: "Admin Panel, Games & Course Content",
        duration: "Ongoing",
        status: "in-progress",
      },
    ],
    team: "Solo Project",
    role: "Full Stack Developer",
    status: "In Active Development",
    duration: "Ongoing",
  },
  {
    id: 12,
    title: "SpeedCopy",
    image: null,
    description:
      "Multi-vendor print and document service marketplace with live pricing, custom design services, and pickup/delivery order flow",
    tech: [
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "Razorpay",
      "Cloudinary",
      "Twilio",
      "Google Maps API",
      "Socket.IO",
      "Sharp",
    ],
    category: "E-commerce / Service Marketplace",
    year: "2026",
    summary:
      "A print and document-service marketplace where customers upload files, get live pricing, and order printing, binding, or custom design work.",
    fullDescription:
      "SpeedCopy is a multi-vendor platform for print and document services. Customers upload PDFs and get automatic page detection and live price calculation for standard printing, spiral binding, soft binding, and thesis binding, alongside custom design services. Orders flow through a full lifecycle with pickup or delivery options and OTP verification. The backend is a Node/Express microservice monorepo split into auth, product, and design services behind a gateway, with Razorpay for payments, Cloudinary and Sharp for image handling, Twilio for notifications, and Google Maps for location-based logistics.",
    features: [
      "PDF upload with automatic page-count detection and manual override",
      "Live price calculation across standard printing, spiral binding, soft binding, and thesis binding",
      "Custom design service ordering alongside standard print services",
      "Full order lifecycle: cart, checkout, pickup/delivery, OTP verification, processing, completion",
      "Node/Express microservice backend split into auth, product, and design services behind a gateway",
      "Razorpay payment integration",
      "Cloudinary and Sharp for image processing and storage",
      "Twilio-powered order and OTP notifications",
      "Google Maps integration for location-based pickup/delivery",
      "Admin and vendor portals for order and catalog management",
    ],
    challenges: [
      "Building a live pricing engine that adapts to multiple service types and configurable options",
      "Designing a microservice split (auth/product/design) behind a single gateway with bundled and per-service run modes",
      "Handling PDF page-count detection and validation reliably across file types",
      "Coordinating an order lifecycle that spans cart, payment, OTP verification, and pickup/delivery logistics",
      "Integrating multiple third-party services (Razorpay, Cloudinary, Twilio, Google Maps) into one coherent checkout flow",
    ],
    liveLink: "",
    githubLink: "",
    timeline: [
      {
        phase: "Pricing Engine & Order Flow Design",
        duration: "Ongoing",
        status: "in-progress",
      },
      {
        phase: "Backend Microservices (Auth, Product, Design)",
        duration: "Ongoing",
        status: "in-progress",
      },
      {
        phase: "Vendor & Admin Portals",
        duration: "Ongoing",
        status: "in-progress",
      },
    ],
    team: "Solo Project",
    role: "Full Stack Developer",
    status: "In Development",
    duration: "Ongoing",
  },
  {
    id: 0,
    title: "RouteLink",
    image: routelink,
    description:
      "Peer-to-peer delivery and travel coordination platform that matches senders with travelers through a mobile app backed by a scalable microservice architecture",

    tech: [
      "React Native",
      "Expo",
      "TypeScript",
      "Next.js",
      "React 19",
      "Fastify",
      "Prisma",
      "PostgreSQL",
      "Zustand",
      "NativeWind",
      "JWT",
      "Twilio",
      "Google OAuth",
      "Razorpay",
      "Nodemailer",
      "Docker",
    ],
    category: "Mobile App + Microservice Platform",
    year: "2026",
    summary:
      "RouteLink is a trust-first logistics platform for posting routes, booking package space, verifying users, and managing payments in real time.",
    fullDescription:
      "RouteLink is a full-stack logistics and mobility platform designed to help people send packages through travelers already heading in the same direction. I built the project as a mobile-first experience using React Native and Expo, supported by a microservice backend for authentication, routes, users, chat, payments, and notifications. The platform includes OTP-based authentication, DigiLocker-inspired identity verification, route posting and discovery, route request handling for both rides and packages, secure payment intent creation, user reputation tracking, and direct messaging between participants. I also created a separate Next.js marketing website to present the product story, feature set, and trust-focused onboarding experience.",

    features: [
      "OTP-based login and signup flow with Twilio-powered phone verification",
      "Mobile-first app built with React Native, Expo, TypeScript, and NativeWind",
      "Microservice architecture with separate auth, user, route, chat, payment, and notification services",
      "Route posting flow for travelers with departure city, destination, timing, transport mode, seating, and pricing",
      "Smart route discovery and search for senders looking for verified travelers",
      "Route request system supporting both ride booking and package delivery use cases",
      "Trust and verification workflow with DigiLocker-style identity verification",
      "User profile, trust score, rating, and reviews management",
      "Secure payment intent creation and status polling with Razorpay",
      "Chat rooms and direct messaging between route participants",
      "Notification system designed for SMS, email, and push-style communication",
      "JWT-based session handling with refresh token support",
      "Separate Next.js landing website to showcase the product and drive adoption",
      "Dockerized local development setup for running multiple backend services together",
    ],
    challenges: [
      "Designing a clean microservice architecture instead of a single monolithic backend",
      "Coordinating communication between multiple services with separate responsibilities and schemas",
      "Implementing secure OTP authentication, token issuance, and refresh flows",
      "Handling trust-sensitive user verification in a logistics product where identity matters",
      "Structuring PostgreSQL and Prisma schemas across multiple independent services",
      "Building a polished mobile UI while integrating live backend APIs and async state flows",
      "Creating a flexible route request model that supports both passenger rides and package delivery",
      "Implementing payment intent creation and live payment status polling with Razorpay",
      "Managing chat, notifications, and profile reputation as separate but connected product flows",
      "Keeping development and testing manageable across Docker, local services, and mobile app environments",
    ],
    liveLink: "https://movi-rose.vercel.app/",
    githubLink: "https://github.com/Sachinsen7/routelink",
    timeline: [
      {
        phase: "Product Planning & System Architecture",
        duration: "4 days",
        status: "completed",
      },
      {
        phase: "Backend Microservices & Database Design",
        duration: "2 weeks",
        status: "completed",
      },
      {
        phase: "Mobile App UI & API Integration",
        duration: "2 weeks",
        status: "completed",
      },
      {
        phase: "Payments, Verification, Chat & Notifications",
        duration: "1 week",
        status: "completed",
      },
      {
        phase: "Marketing Website & Final Polish",
        duration: "4 days",
        status: "completed",
      },
    ],
    team: "Solo Project",
    role: "Full Stack Developer",
    status: "In Active Development",
    duration: "1 month",
  },
  {
    id: 1,
    title: "Monositi",
    image: monositi,
    description:
      "Full-stack property rental and service provider marketplace platform with real-time geolocation and OTP authentication",

    tech: [
      "React 19",
      "Node.js",
      "Express",
      "MongoDB",
      "Redux Toolkit",
      "Tailwind CSS",
      "Vite",
      "JWT",
      "Cloudinary",
      "Twilio",
      "Vercel",
      "Framer Motion",
    ],
    category: "Full Stack Web Application",
    year: "2025",
    summary:
      "Comprehensive property rental and service marketplace platform with advanced search",
    fullDescription:
      "Monositi is a modern full-stack marketplace platform that connects property owners, tenants, and service providers. Built with React 19 and Node.js, it features a robust authentication system with OTP verification via Twilio, real-time geolocation-based property search, and a comprehensive service booking system. The platform supports multiple user roles (Tenant, Landlord, Service Provider, Admin) with role-based access control and includes advanced features like KYC verification, property document management, and service provider ratings.",
    features: [
      "Multi-role authentication system with OTP verification via WhatsApp/SMS",
      "Real-time geolocation-based property and service search",
      "Advanced property listing with image and document management via Cloudinary",
      "Service provider marketplace with booking and rating system",
      "Admin dashboard for user and property verification",
      "KYC document upload and verification workflow",
      "Responsive design with Tailwind CSS and Framer Motion animations",
      "Redux Toolkit for state management",
      "RESTful API with JWT authentication and role-based authorization",
      "Property filtering by type, location, price range, and amenities",
      "Service booking with availability calendar and add-ons",
      "User profile management with subscription plans",
      "Real-time notifications and contact preferences",
    ],
    challenges: [
      "Implementing secure multi-role authentication with OTP verification using Twilio",
      "Building geolocation-based search with MongoDB geospatial queries",
      "Managing complex file uploads for properties and services with Cloudinary integration",
      "Designing scalable RESTful API architecture with proper error handling",
      "Implementing role-based access control across frontend and backend",
      "Creating responsive UI with smooth animations using Framer Motion",
      "Handling CORS configuration for multiple deployment environments",
      "Optimizing image loading and performance for property listings",
    ],
    liveLink: "https://monositi-new.vercel.app",
    githubLink: "https://github.com/Sachinsen7/monositi-new",
    timeline: [
      {
        phase: "Planning & Architecture Design",
        duration: "2 weeks",
        status: "completed",
      },
      {
        phase: "Backend API Development",
        duration: "4 weeks",
        status: "completed",
      },
      {
        phase: "Frontend Development & Integration",
        duration: "5 weeks",
        status: "completed",
      },
      {
        phase: "Testing, Bug Fixes & Optimization",
        duration: "2 weeks",
        status: "completed",
      },
      {
        phase: "Deployment & Production Setup",
        duration: "1 week",
        status: "completed",
      },
    ],
    team: "Team Project",
    role: "Full Stack Developer",
    status: "Live & Maintained",
    duration: "3.5 months",
  },
  {
    id: 2,
    title: "Cloud SaaS Media Platform",
    image: cloud_saas,
    description:
      "A comprehensive Next.js-based SaaS platform with advanced media processing, AI-powered image analysis, and document conversion capabilities",
    tech: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Cloudinary",
      "Tailwind CSS",
      "Prisma",
      "PostgreSQL",
      "Azure AI",
      "Clerk",
    ],
    category: "SaaS Platform",
    year: "2025",
    summary:
      "Enterprise-grade media processing SaaS platform with AI capabilities",
    fullDescription:
      "A comprehensive Next.js-based SaaS platform that provides advanced media processing, AI-powered image analysis, and document conversion capabilities. Built with modern web technologies and integrated with Cloudinary's powerful media management services. This platform combines video processing, AI-powered image analysis, document conversion, and social media content creation into a unified SaaS solution.",
    features: [
      "Video upload, processing, and compression with analytics",
      "AI-powered background removal with fine-edge options",
      "OCR text extraction from images and documents",
      "Smart auto-tagging and image enhancement using VIESUS technology",
      "Advanced facial analysis with Azure AI Services (up to 64 faces)",
      "Office document conversion (Word, Excel, PowerPoint to PDF)",
      "Social media content creator with format transformation",
      "AI vision analysis with custom tagging and content moderation",
      "Watermark detection and quality assessment",
      "Real-time conversion progress monitoring",
      "Secure media delivery with signed URLs",
    ],
    challenges: [
      "Integrating multiple AI services (Cloudinary, Azure AI, VIESUS, Aspose)",
      "Building scalable media processing pipeline",
      "Implementing real-time progress tracking for document conversion",
      "Managing complex authentication and authorization with Clerk",
      "Optimizing performance for large media file processing",
      "Creating responsive UI for diverse media management workflows",
    ],
    liveLink: "https://cloud-saas-five.vercel.app/",
    githubLink: "https://github.com/Sachinsen7/cloud-saas",
    timeline: [
      {
        phase: "Architecture & Planning",
        duration: "2 weeks",
        status: "completed",
      },
      {
        phase: "Authentication & Database Setup",
        duration: "1 week",
        status: "completed",
      },
      {
        phase: "Core Media Processing",
        duration: "4 weeks",
        status: "completed",
      },
      {
        phase: "AI Integration (Cloudinary, Azure)",
        duration: "3 weeks",
        status: "completed",
      },
      {
        phase: "Document Conversion System",
        duration: "2 weeks",
        status: "completed",
      },
      {
        phase: "Frontend UI/UX Development",
        duration: "3 weeks",
        status: "completed",
      },
      {
        phase: "Testing & Optimization",
        duration: "2 weeks",
        status: "completed",
      },
      { phase: "Deployment & Launch", duration: "1 week", status: "completed" },
    ],
    team: "Solo Project",
    role: "Full Stack Developer & Solution Architect",
    status: "Live & Maintained",
    duration: "4 months",
  },
  {
    id: 3,
    title: "EndPointHub",
    image: endpointhub,
    description:
      "Lightweight API marketplace for developers to publish, discover, and consume APIs with ease",
    tech: [
      "Next.js 14",
      "React",
      "TypeScript",
      "Redux Toolkit",
      "RTK Query",
      "Tailwind CSS",
      "Node.js",
      "Express",
      "PostgreSQL",
      "Prisma",
      "Redis",
      "JWT",
      "Docker",
      "Swagger UI",
      "Zod",
      "Framer Motion",
    ],
    category: "API Management",
    year: "2025",
    summary: "Free-first API marketplace with authentication and rate limiting",
    fullDescription:
      "EndpointHub is a lightweight and free-first API marketplace designed for developers to publish, discover, and consume APIs with ease. It features user authentication, API key management, secure request proxying with rate limiting, and interactive documentation. Built entirely with free and open-source technologies.",
    features: [
      "User registration/login with JWT authentication",
      "Publish APIs with OpenAPI/Swagger docs",
      "Generate and revoke API keys per user and API",
      "Proxy API requests with key validation and rate limiting",
      "Interactive API documentation viewer",
      "Usage analytics dashboard (requests, errors, latency)",
      "Responsive UI with light/dark mode support",
      "Redis caching for performance optimization",
    ],
    challenges: [
      "Building secure API key management system",
      "Implementing rate limiting with Redis",
      "Creating interactive API documentation viewer",
      "Designing scalable proxy architecture",
      "Integrating comprehensive analytics tracking",
    ],
    liveLink: "https://endpointhub.vercel.app",
    githubLink: "https://github.com/Sachinsen7/EndPointHub",
    timeline: [
      { phase: "Planning & Research", duration: "1 week", status: "completed" },
      { phase: "Core Development", duration: "4 weeks", status: "completed" },
      { phase: "Testing Features", duration: "2 weeks", status: "completed" },
      { phase: "UI/UX Polish", duration: "1 week", status: "completed" },
    ],
    team: "Solo Project",
    role: "Full Stack Developer",
    status: "In Development",
    duration: "2 months",
  },
  {
    id: 4,
    title: "Code Editor",
    image: ecommerce,
    description:
      "Web-based code editor with syntax highlighting and collaboration",
    tech: ["React", "Node.js", "Socket.io", "Monaco Editor"],
    category: "Developer Tools",
    year: "2025",
    summary: "Collaborative web-based code editor",
    fullDescription:
      "A feature-rich web-based code editor with real-time collaboration, syntax highlighting, and integrated terminal. Designed for developers who need a powerful online coding environment.",
    features: [
      "Syntax highlighting for multiple languages",
      "Real-time collaborative editing",
      "Integrated terminal and file explorer",
      "Code completion and IntelliSense",
      "Theme customization",
      "Plugin system for extensions",
    ],
    challenges: [
      "Implementing real-time collaborative editing",
      "Building robust syntax highlighting system",
      "Creating responsive editor interface",
      "Integrating terminal functionality",
    ],
    liveLink: "",
    githubLink: "",
    timeline: [
      { phase: "Editor Setup", duration: "1 week", status: "completed" },
      {
        phase: "Collaboration Features",
        duration: "2 weeks",
        status: "completed",
      },
      {
        phase: "Terminal Integration",
        duration: "1 week",
        status: "completed",
      },
      { phase: "UI/UX Enhancement", duration: "1 week", status: "completed" },
    ],
    team: "Solo Project",
    role: "Full Stack Developer",
    status: "Portfolio Project",
    duration: "1.5 months",
  },
  {
    id: 5,
    title: "Kia Project",
    image: ecommerce,
    description: "Modern automotive showcase platform with interactive features",
    tech: ["React", "Node.js", "Express", "MongoDB"],
    category: "Automotive",
    year: "2025",
    summary: "Interactive automotive platform for Kia vehicle showcase",
    fullDescription: "Developed a comprehensive automotive platform for Kia featuring vehicle showcases, interactive configurators, and dealer management system. The platform provides immersive user experience with 360° vehicle views and advanced filtering capabilities.",
    features: [
      "Interactive vehicle configurator with real-time pricing",
      "360° vehicle showcase with detailed specifications",
      "Dealer locator with appointment booking system",
      "Advanced search and filtering by model, price, features",
      "Virtual test drive scheduling",
      "Financing calculator and loan application",
      "Service booking and maintenance tracking",
      "Admin dashboard for inventory management"
    ],
    challenges: [
      "Implementing 360° vehicle visualization",
      "Building real-time pricing configurator",
      "Creating responsive design for all device types",
      "Integrating dealer management system"
    ],
    liveLink: "",
    githubLink: "",
    timeline: [
      { phase: "Design & Planning", duration: "2 weeks", status: "completed" },
      { phase: "Frontend Development", duration: "6 weeks", status: "completed" },
      { phase: "Backend API", duration: "4 weeks", status: "completed" },
      { phase: "Integration & Testing", duration: "2 weeks", status: "completed" },
      { phase: "Deployment & Launch", duration: "1 week", status: "completed" }
    ],
    team: "Solo Project",
    role: "Full Stack Developer",
    status: "Portfolio Project",
    duration: "3 months"
  },
  {
    id: 6,
    title: "Class Crew",
    image: classcrew,
    description: "Student collaboration platform with assignment tracking and group management",
    tech: ["React", "Node.js", "MongoDB", "Socket.io", "Express"],
    category: "Education",
    year: "2025",
    summary: "Collaborative platform for student project management and teamwork",
    fullDescription: "Class Crew is a comprehensive student collaboration platform designed to enhance teamwork and project management in educational settings. Features real-time collaboration, assignment tracking, group formation, and progress monitoring tools.",
    features: [
      "Real-time collaboration with live document editing",
      "Assignment tracking and deadline management",
      "Automated group formation based on skills and preferences",
      "Progress monitoring with visual analytics",
      "File sharing and version control system",
      "Discussion forums and chat functionality",
      "Teacher dashboard for class oversight",
      "Grade tracking and performance analytics"
    ],
    challenges: [
      "Implementing real-time collaboration features",
      "Building intelligent group formation algorithms",
      "Creating intuitive project management interface",
      "Ensuring scalable real-time communication"
    ],
    liveLink: "https://crew-frontend-amber.vercel.app/",
    githubLink: "",
    timeline: [
      { phase: "Research & Planning", duration: "1 week", status: "completed" },
      { phase: "UI/UX Design", duration: "2 weeks", status: "completed" },
      { phase: "Backend Development", duration: "4 weeks", status: "completed" },
      { phase: "Frontend Development", duration: "5 weeks", status: "completed" },
      { phase: "Real-time Features", duration: "2 weeks", status: "completed" },
      { phase: "Testing & Launch", duration: "1 week", status: "completed" }
    ],
    team: "Solo Project",
    role: "Full Stack Developer",
    status: "Live & Active",
    duration: "3 months"
  },
  {
    id: 7,
    title: "ADRS Gem Control",
    image: gem_control,
    description: "Jewellery business management with inventory and barcode generation",
    tech: ["React", "Node.js", "MongoDB", "Express", "Material UI", "Redux"],
    category: "E-commerce",
    year: "2025",
    summary: "Comprehensive jewellery business management with e-commerce integration",
    fullDescription: "Developed a full-stack web application for jewellery business management, featuring inventory, sales, and real-time dashboards with barcode generation.",
    features: [
      "Advanced inventory management with barcode generation",
      "Sales tracking and comprehensive analytics",
      "Customer relationship management system",
      "E-commerce integration with online catalog",
      "Real-time dashboard with business insights",
      "Product catalog with detailed specifications",
      "Invoice generation and billing system",
      "Multi-location inventory tracking"
    ],
    challenges: [
      "Handling complex jewellery product specifications",
      "Implementing barcode generation and scanning system",
      "Building real-time inventory synchronization",
      "Creating intuitive UI for non-technical users"
    ],
    liveLink: "",
    githubLink: "",
    timeline: [
      { phase: "Business Analysis", duration: "2 weeks", status: "completed" },
      { phase: "Database Design", duration: "1 week", status: "completed" },
      { phase: "Backend Development", duration: "6 weeks", status: "completed" },
      { phase: "Frontend Development", duration: "8 weeks", status: "completed" },
      { phase: "Barcode Integration", duration: "2 weeks", status: "completed" },
      { phase: "Testing & Deployment", duration: "1 week", status: "completed" }
    ],
    team: "Solo Project",
    role: "Full Stack Developer",
    status: "Client Delivered",
    duration: "3 months"
  },
  {
    id: 8,
    title: "Techora",
    image: learnsphere,
    description:
      "Online learning platform with course management and progress tracking",
    tech: ["React", "Framer Motion", "Express", "Redux", "Node.js", "MongoDB"],
    category: "Education",
    year: "2025",
    summary: "Online learning platform",
    fullDescription:
      "Techora is a comprehensive online learning platform that enables educators to create, manage, and sell courses while providing students with an engaging learning experience. Features include video streaming, progress tracking, quizzes, and certification systems.",
    features: [
      "Course creation and management",
      "Video streaming and playback",
      "Student progress tracking",
      "Interactive quizzes and assessments",
      "Certificate generation",
      "Payment processing for course sales",
    ],
    challenges: [
      "Implementing video streaming infrastructure",
      "Building comprehensive progress tracking system",
      "Creating interactive assessment tools",
      "Designing user-friendly course creation interface",
    ],
    liveLink: "",
    githubLink: "",
    timeline: [
      { phase: "UI/UX Design", duration: "1 week", status: "completed" },
      {
        phase: "Frontend Development",
        duration: "3 weeks",
        status: "completed",
      },
      { phase: "Backend API", duration: "2 weeks", status: "completed" },
      { phase: "Video Integration", duration: "1 week", status: "completed" },
      { phase: "Testing & Launch", duration: "1 week", status: "completed" },
    ],
    team: "Solo Project",
    role: "Full Stack Developer",
    status: "Portfolio Project",
    duration: "2 months",
  },
  {
    id: 9,
    title: "Dish Discovery App",
    image: recipe_finder,
    description:
      "Recipe finder with nutritional information and cooking instructions",
    tech: ["React", "Tailwind CSS"],
    category: "Lifestyle",
    year: "2025",
    summary: "Recipe Finder App",
    fullDescription:
      "A feature-rich recipe discovery platform that helps users find, save, and share recipes. Integrated with the Spoonacular API to provide access to thousands of recipes with detailed nutritional information, cooking instructions, and ingredient lists.",
    features: [
      "Recipe search and filtering",
      "Nutritional information display",
      "Ingredient-based recipe suggestions",
      "Favorite recipes collection",
      "Cooking timer and instructions",
      "Dietary restriction filters",
    ],
    challenges: [
      "Integrating third-party recipe API",
      "Implementing efficient search and filtering",
      "Creating responsive recipe card layouts",
      "Managing large datasets of recipe information",
    ],
    liveLink: "",
    githubLink: "",
    timeline: [
      { phase: "API Research", duration: "3 days", status: "completed" },
      {
        phase: "Frontend Development",
        duration: "2 weeks",
        status: "completed",
      },
      { phase: "API Integration", duration: "1 week", status: "completed" },
      { phase: "UI Polish", duration: "3 days", status: "completed" },
    ],
    team: "Solo Project",
    role: "Full Stack Developer",
    status: "Portfolio Project",
    duration: "1 month",
  },
  {
    id: 10,
    title: "Melody Heaven",
    image: music_player,
    description: "Music streaming platform with playlist management",
    tech: ["HTML", "CSS", "Javascript", "Node.js"],
    category: "Entertainment",
    year: "2024",
    summary: "Music Player",
    fullDescription:
      "Melody Heaven is a sophisticated music streaming platform that combines beautiful design with powerful functionality. Features include playlist creation, social sharing, music discovery, and high-quality audio streaming with a focus on user experience.",
    features: [
      "High-quality music streaming",
      "Playlist creation and management",
      "Music discovery algorithms",
      "Social sharing features",
      "Offline listening capability",
      "Artist and album information",
    ],
    challenges: [
      "Implementing audio streaming infrastructure",
      "Building playlist management system",
      "Creating music discovery algorithms",
      "Designing intuitive user interface",
    ],
    liveLink: "",
    githubLink: "",
    timeline: [
      {
        phase: "Design & Prototyping",
        duration: "1 week",
        status: "completed",
      },
      { phase: "Audio System Setup", duration: "2 weeks", status: "completed" },
      {
        phase: "Frontend Development",
        duration: "3 weeks",
        status: "completed",
      },
      { phase: "Backend & Database", duration: "2 weeks", status: "completed" },
      {
        phase: "Testing & Optimization",
        duration: "1 week",
        status: "completed",
      },
    ],
    team: "Solo Project",
    role: "Full Stack Developer",
    status: "Portfolio Project",
    duration: "2 months",
  },
];
